import os
import argparse
import pandas as pd
from tqdm import tqdm
import time
import google.generativeai as genai

# ==========================================
# Prompt Template
# ==========================================
OPTIMIZED_PROMPT = '''
Please complete the following tasks based on the two video clips I provide:
1.  First, you need to describe the content of these two video segments in detail, then perform a relevance analysis to confirm whether these two videos meet:
<<Visual Relevance Criteria>>:
(1) Spatial Consistency (2) Subject Consistency (3) Perspective Continuity (4) Time Indicators (5) Dynamic Element Trajectory
<<Logical Relevance Criteria>>:
(1) Time Sequence (2) Causal Relationship (3) Spatial Transition (4) State Change
(5) Parallel Comparison (6) Conceptual Metaphor
2.  If step 1 meets at least 1 visual relevance criterion + 1 logical relevance criterion, then you need to simulate a human's [video generation instruction], instructing the model to actively extract key information from the first video and generate the second video through logical reasoning (e.g., causal relationships of events, spatial transitions) or by incorporating world knowledge (e.g., physical/chemical laws, temporal/spatial knowledge). The instruction should not contain descriptions of Video 1 and Video 2, but should guide the model to autonomously analyze the content of Video 1, extract key information, and generate a reasonable Video 2.
If step 1 does not meet the requirements, please end directly without generating a simulated instruction.
3.  You also need to provide the model's thinking process and the final ground truth caption (i.e., the description of Video 2). The simulated thinking process should follow this logic: first summarize and describe the input video, then provide necessary world knowledge and plot supplements, and finally perform logical deduction (but do not explicitly list points; organize it into a paragraph).
4.  Finally, conduct a review.

Output Format:
[Video 1 Description] <Detailed description>
[Video 2 Description] <Detailed description>
[Relation Analysis]
- Visual Relevance: <List the 5 types and judge whether each is met or not>
- Logical Relevance: <List the 6 types and judge whether each is met or not>
[Instruction] <Natural language video generation instruction>
[Think] <Simulated model thinking process>
[GT Caption] <Caption suitable for the video generation model, based on the Video 2 description>

Excellent Examples:
Example 1:
[Instruction] Show the scene that would be seen from the runner's forward perspective in the video.
[Think] Okay, the input video shows a man in red sportswear running on a park track, breathing heavily. According to the laws of motion, a runner's line of sight will slightly fluctuate up and down with their body. Judging by the running direction, the track should extend ahead, and the breathing state will affect the stability of the line of sight.
[Caption] A slightly shaky perspective shows an extending park track, with trees on both sides moving backward rapidly.
[Review]
- Instruction Compliance: Pass ...
- Logical Rigor: Pass ...
- Thinking Process: Pass ...

Example 2:
[Instruction] What would happen if this glass continues to tilt?
[Think] The video shows a hand holding a glass full of water beginning to tilt. Liquids maintain a horizontal surface under gravity; when the angle exceeds 45 degrees, water will spill out due to gravity, first flowing from the lowest point of the rim.
[Caption] Water flows out from the tilted glass rim, forming spreading water stains on the table.
[Review]
- Instruction Compliance: Pass ...
- Logical Rigor: Pass ...
- Thinking Process: Pass ...

Example 3:
[Instruction] What would the boy in the video do next if he felt sleepy?
[Think] From the input video, I see a boy walking in the living room. If a person feels sleepy, they should go to sleep. The white door in the video likely leads to the bedroom, so the boy should next walk towards the bedroom and open the door.
[Caption] The boy opens the white door to the bedroom (description of the bedroom).
[Review]
- Instruction Compliance: Pass ...
- Logical Rigor: Pass ...
- Thinking Process: Pass ...

Key Points:
- Ignore audio information.

After this, you need to check whether the [Instruction] and [Think] generated by the preceding model comply with the specifications.

### Review Criteria
1.  Instruction Compliance Check
   - ❌ Forbidden: The [Instruction] contains specific descriptions of Video 1 or Video 2 (e.g., "The man in video 1 is running, what will happen next?")
   - ✅ Requirement: Preferably use hypotheses to increase reasoning difficulty: e.g., "If a sudden noise came from downstairs, what would this man do? -> The man goes downstairs." "If this man had back pain at this moment, what would he do? -> The man would stand up."

2.  Logical Rigor Review:
   - ❌ Forbidden: The logical connection between the instruction and the result (Video 2) is weak or overly broad.
   - ✅ Requirement: The instruction's logic must be rigorous and highly deterministic, ensuring the target model can derive a unique Video 2 generation result based solely on the input Video 1 and the given instruction.

3.  Thinking Process Review:
   - ❌ Forbidden: The model must not reference any information from Video 2 during reasoning (because the model input does not include Video 2). Explicit references like "as known from Video 2," "compared with Video 2," etc., are strictly prohibited.
   - ✅ Requirement: The thinking process must include:
     - Key information extraction from Video 1 (e.g., "a runner in red clothes")
     - Logical bridge (e.g., "the line of sight fluctuates with the body during running")
     - World knowledge reference (e.g., "liquids spill at a 45-degree tilt angle")

### Review Process
1.  If it passes the review: Output [Valid] with brief reasons for approval.
2.  If it does not pass the review:
   - Output [Invalid] and point out the specific problem(s).
   - Provide modified [Instruction], [Think], and [GT Caption] from another angle or corrected.

### Output Format
[Review]
- Instruction Compliance: <Pass/Fail, reason>
- Logical Rigor: <Pass/Fail, reason>
- Thinking Process: <Pass/Fail, reason>
[Corrected Instruction] (if needed) <Corrected instruction>
[Corrected Think] (if needed) <Corrected reasoning process>
[Corrected GT Caption] (if needed) <Corrected correct GT>

### Review Example
[Input]
[Instruction] The cup in video 1 is tilting, what will happen next?
[Think] The water will flow out after the cup tilts.
[GT Caption] ...
[Output]
[Review]
- Instruction Compliance: Fail (instruction mentions specific content of Video 1)
- Logical Rigor: Pass (causal relationship is valid)
- Thinking Process: Pass
[Corrected Instruction] What would happen if this action continues?
[Corrected Think] The input video shows a container undergoing angular change. According to fluid dynamics principles, when the container's tilt angle exceeds a critical value, the liquid will spill over the edge of the container due to gravity.
[Corrected GT Caption] ...

Now please start generating, then review:
'''

def upload_to_gemini(path, mime_type=None):
    """Uploads the given file to Gemini."""
    file = genai.upload_file(path, mime_type=mime_type)
    return file

def main(args):
    # Setup API Key
    keys_string = args.api_keys or os.environ.get("GEMINI_API_KEYS", "") or os.environ.get("GEMINI_API_KEY", "")
    api_key_list = [k.strip() for k in keys_string.split(',') if k.strip()]
    if not api_key_list:
        raise ValueError("No API keys provided! Please set the GEMINI_API_KEYS environment variable.")
    genai.configure(api_key=api_key_list)
    
    model = genai.GenerativeModel('gemini-2.5-flash')
    
    os.makedirs(args.output_dir, exist_ok=True)
    df = pd.read_csv(args.input_csv)
    
    for index, row in tqdm(df.iterrows(), total=len(df), desc="Generating Predictive Instructions"):
        video1_path = row['video1_path']
        video2_path = row['video2_path']
        
        if not os.path.exists(video1_path) or not os.path.exists(video2_path):
            continue
            
        output_txt_path = os.path.join(args.output_dir, f"pair_{index:04d}.txt")
        if os.path.exists(output_txt_path):
            continue

        try:
            # Upload files
            video1_file = upload_to_gemini(video1_path)
            video2_file = upload_to_gemini(video2_path)
            
            # Generate content
            response = model.generate_content(
                [video1_file, video2_file, OPTIMIZED_PROMPT],
                request_options={"timeout": 600}
            )
            predicted_answer = response.text
            
            # Cleanup uploaded files
            genai.delete_file(video1_file.name)
            genai.delete_file(video2_file.name)
            
            # Save valid results
            if "[GT Caption]" in predicted_answer:
                with open(output_txt_path, "w", encoding="utf-8") as file:
                    file.write(f"Video1: {video1_path}\nVideo2: {video2_path}\n\n")
                    file.write(predicted_answer)
                    
        except Exception as e:
            print(f"Error processing pair {index}: {e}")
            time.sleep(5)
            continue

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate predictive instructions from video pairs')
    parser.add_argument('--input_csv', type=str, required=True, help='CSV containing video1_path and video2_path')
    parser.add_argument('--output_dir', type=str, required=True, help='Output directory for txt files')
    parser.add_argument('--api_keys', type=str, help='Comma-separated API keys')
    args = parser.parse_args()
    main(args)