import os
import time
import argparse
from tqdm import tqdm
import google.generativeai as genai

# ==========================================
# Full Review & Rewrite Prompt (English Version)
# ==========================================
REVIEW_PROMPT = '''
You are a strict video logical correlation reviewer. Your task is to check whether the [Instruction] and [Think] generated by the previous model comply with the rules, and provide the final bilingual (English and Chinese) versions.

### Review Criteria
1. Instruction Compliance Check
   - ❌ PROHIBITED: Specific visual descriptions of Video 1 or Video 2 appearing in the [Instruction] (e.g., "The man in video 1 is running, what happens next?").
   - ✅ REQUIRED: Use hypothetical scenarios to increase reasoning difficulty. Example: "If a sudden noise came from downstairs, what would this man do? -> The man goes downstairs." or "If a figure appeared at the window, what would the man do? -> The man looks out."
2. Logical Rigor Review
   - ❌ PROHIBITED: Weak or overly broad logical correlation between the instruction and the outcome (Video 2).
   - ✅ REQUIRED: The logic MUST be rigorous and highly deterministic. Ensure the target model can deduce the *unique* Video 2 outcome solely based on Video 1 and the instruction.
3. Thinking Process Review
   - ❌ PROHIBITED: The reasoning process must NOT reference Video 2 at all (since Video 2 is not part of the input). Explicit phrases like "Video 2 shows" or "From Video 2" are strictly forbidden.
   - ✅ REQUIRED: The [Think] process must include:
     - Key information extraction from Video 1 (e.g., "runner in red").
     - A logical bridge (e.g., "line of sight bobs while running").
     - World knowledge citation (e.g., "liquid spills when tilted past 45 degrees").

### Review Process
1. If passed: Output [Valid] and briefly state the reason.
2. If failed:
   - Output [Invalid] and point out the specific violations.
   - Provide a corrected/alternative [Instruction], [Think], and [GT Caption].

### Translation Process
Provide the final corrected versions in both Chinese and English using the following exact tags:

### Output Format
[Review]
- Instruction Compliance: <Pass/Fail, Reason>
- Logical Rigor: <Pass/Fail, Reason>
- Thinking Process: <Pass/Fail, Reason>
[CHN Instruction] <Final Chinese Instruction>
[CHN Think] <Final Chinese Reasoning>
[CHN GT Caption] <Final Chinese GT Caption>
[ENG Instruction] <Final English Instruction>
[ENG Think] <Final English Reasoning>
[ENG GT Caption] <Final English GT Caption>

### Example
[Input]
[Instruction] The cup in Video 1 is tilting, what will happen next?
[Think] The water will flow out after the cup tilts.
[GT Caption] ...

[Output]
[Review]
- Instruction Compliance: Fail (Instruction explicitly mentions Video 1 content)
- Logical Rigor: Pass (Causal relationship holds)
- Thinking Process: Pass 
[CHN Instruction] 如果继续这个动作会发生什么？
[CHN Think] 输入视频显示容器发生角度变化。根据流体力学原理，当容器倾角超过临界值时，液体因重力作用会从容器边缘溢出。
[CHN GT Caption] ...
[ENG Instruction] What will happen if this action continues?
[ENG Think] The input video shows a container undergoing angular displacement. According to fluid dynamics principles, when the container's tilt angle exceeds a critical threshold, the liquid will spill over the edge due to gravity.
[ENG GT Caption] ...

Now, please review the following content:
\n\n[Original Content]:\n{original_content}
'''

def main(args):
    # Setup API Keys
    keys_string = args.api_keys or os.environ.get("GEMINI_API_KEYS", "") or os.environ.get("GEMINI_API_KEY", "")
    api_key_list = [k.strip() for k in keys_string.split(',') if k.strip()]
    if not api_key_list:
        raise ValueError("No API keys provided!")
    
    # Randomize or select key based on logic (simplified for standard load balancing)
    genai.configure(api_key=api_key_list)
    model = genai.GenerativeModel('gemini-2.5-pro')
    
    os.makedirs(args.output_dir, exist_ok=True)
    
    txt_files = [f for f in os.listdir(args.input_dir) if f.endswith('.txt')]
    # Handle slicing
    start_idx = int(len(txt_files) * args.start_idx)
    end_idx = int(len(txt_files) * args.end_idx)
    txt_files = txt_files[start_idx:end_idx]
    
    for filename in tqdm(txt_files, desc="Reviewing and Modifying"):
        input_txt_path = os.path.join(args.input_dir, filename)
        output_txt_path = os.path.join(args.output_dir, filename)
        
        if os.path.exists(output_txt_path):
            continue
            
        with open(input_txt_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        if '[Review]' in content:
            content = content[:content.find('[Review]')]
            
        formatted_prompt = REVIEW_PROMPT.format(original_content=content)
        
        try:
            response = model.generate_content(formatted_prompt, request_options={"timeout": 60})
            predicted_answer = response.text
            
            with open(output_txt_path, "w", encoding="utf-8") as file:
                file.write(predicted_answer)
                
        except Exception as e:
            print(f"Error processing {filename}: {e}")
            if 'PROHIBITED_CONTENT' in str(e):
                with open(output_txt_path, "w", encoding="utf-8") as file:
                    file.write("PROHIBITED_CONTENT")
            time.sleep(10)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Check, modify, and translate generated instructions')
    parser.add_argument('--input_dir', type=str, required=True, help='Raw instructions folder')
    parser.add_argument('--output_dir', type=str, required=True, help='Modified bilingual instructions folder')
    parser.add_argument('--api_keys', type=str, help='Comma-separated API keys')
    parser.add_argument('--start_idx', type=float, default=0.0)
    parser.add_argument('--end_idx', type=float, default=1.0)
    args = parser.parse_args()
    main(args)