import json
import csv
import os
import re
import ast
import argparse
from tqdm import tqdm 

def process_json_to_csv(json_file_path, output_csv_path, base_folder_path, recipe_csv_path):
    """
    Process the JSON file and generated dense captions to create a master CSV.
    
    Args:
        json_file_path (str): Path to the dataset JSON file.
        output_csv_path (str): Path where the output CSV will be saved.
        base_folder_path (str): Base directory containing the text files generated by Gemini.
        recipe_csv_path (str): Path to the recipe/task mapping CSV.
    """
    # Read the recipe/task mapping into a dictionary
    recipe_mapping = {}
    if os.path.exists(recipe_csv_path):
        with open(recipe_csv_path, 'r', encoding='utf-8') as f:
            for line in f:
                parts = line.strip().split(',')
                if len(parts) >= 2:
                    recipe_mapping[parts] = parts 
        print(f"Loaded {len(recipe_mapping)} recipe mappings.")
    else:
        print(f"Warning: Recipe mapping file not found at {recipe_csv_path}. Using default task names.")

    # Read the main JSON dataset file
    with open(json_file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Create the output CSV and write headers
    with open(output_csv_path, 'w', newline='', encoding='utf-8-sig') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['name', 'recipe_type', 'id', 'sentence', 'video_path', 'dense_caption'])
        
        # Iterate through the JSON data
        for name, video_data in tqdm(data['database'].items(), desc="Merging Data"):
            annotations = video_data.get('annotation', [])
            
            for annotation in annotations:
                annotation_id = annotation.get('id', '')
                sentence = annotation.get('label', '')
                
                # Construct the path to the text file generated in Step 2
                txt_file_path = os.path.join(base_folder_path, name, f"{annotation_id}.txt")
                
                video_path = None
                dense_caption = None
                
                # Check if the text file exists
                if os.path.exists(txt_file_path):
                    try:
                        with open(txt_file_path, 'r', encoding='utf-8') as txt_file:
                            content = txt_file.read()
                            
                            # Update: Match the English output "[Final Conclusion]" instead of Chinese
                            final_conclusion_match = re.search(r'\[Final Conclusion\]:?.*?\[video-(\d+)\]', content, re.DOTALL | re.IGNORECASE)
                            
                            # Extract the last line (which contains the list of video paths)
                            last_line_match = re.findall(r'\[.*?\]', content)
                            if last_line_match:
                                last_line = last_line_match[-1]  # Get the content of the last bracket
                                
                                try:
                                    # Attempt to parse as a Python list
                                    path_list = ast.literal_eval(last_line)
                                    if isinstance(path_list, list) and len(path_list) > 0:
                                        if final_conclusion_match:
                                            # Extract the 'n' in video-n
                                            video_n = int(final_conclusion_match.group(1))
                                            # Use the n-th path (if n is within range)
                                            if 1 <= video_n <= len(path_list):
                                                video_path = path_list[video_n - 1]
                                            else:
                                                video_path = path_list  # Fallback to the first path
                                        else:
                                            video_path = path_list
                                except (ValueError, SyntaxError):
                                    pass # Parsing failed, keep as None
                            
                            # Extract the dense_caption (from the Final Conclusion block)
                            final_conclusion_text_match = re.search(r'\[Final Conclusion\](.*?)(?=\n|$)', content, re.DOTALL | re.IGNORECASE)
                            if final_conclusion_text_match:
                                final_conclusion_text = final_conclusion_text_match.group(1)
                                # Find all bracketed content within the final conclusion
                                all_brackets = re.findall(r'\[([^\]]*)\]', final_conclusion_text)
                                if all_brackets and len(all_brackets) >= 2:
                                    # The dense caption is usually the last bracket in the format [Step][Video][Time][Caption]
                                    dense_caption = all_brackets[-1]  
                                    dense_caption = dense_caption.replace("Video 1", "video").replace("video 1", "video")
                            else:
                                dense_caption = sentence
                                
                            if "none" in str(dense_caption).lower() or "-00" in str(dense_caption).lower():
                                dense_caption = sentence

                    except Exception as e:
                        print(f"Error processing file {txt_file_path}: {e}")
                        video_path = None
                        dense_caption = sentence
                else:
                    # File does not exist, keep as None
                    video_path = None
                    dense_caption = None
                    
                recipe_type = video_data.get('recipe_type', '')
                recipe_name = recipe_mapping.get(str(recipe_type), 'Unknown Task')

                # Write the row to the CSV
                writer.writerow([name, recipe_name, annotation_id, sentence, video_path, dense_caption])
    
    print(f"\nSuccessfully generated CSV file at: {output_csv_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Merge JSON annotations and Gemini text outputs into a master CSV.")
    parser.add_argument("--json_path", type=str, required=True, help="Path to the COIN_OK.json file.")
    parser.add_argument("--output_csv", type=str, required=True, help="Path to save the output COIN_caption.csv.")
    parser.add_argument("--txt_folder", type=str, required=True, help="Directory containing the dense caption txt files from Step 2.")
    parser.add_argument("--recipe_csv", type=str, required=True, help="Path to the recipe mapping CSV (e.g., label_foodtype_coin.csv).")
    
    args = parser.parse_args()
    
    process_json_to_csv(
        json_file_path=args.json_path, 
        output_csv_path=args.output_csv, 
        base_folder_path=args.txt_folder, 
        recipe_csv_path=args.recipe_csv
    )